title: Mi primer sitio Jekyll
description: Este es mi primer sitio usando Jekyll
theme: jekyll-theme-cayman

url: "https://anto9430.github.io"  
baseurl: "/jekyll-sitio"              

header_links:
  - title: Inicio
    url: /
  - title: Sobre mí
    url: /about
  - title: Contacto
    url: /contact

sass:
  quiet: true