title: Mi primer sitio Jekyll
description: Este es mi primer sitio usando Jekyll
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme

header_links:
  - title: Inicio
    url: /
  - title: Sobre mí
    url: /about
  - title: Contacto
    url: /contact

    sass:
      quiet: true
